Feature/universal link
4d/4D-Mobile-App-Server pull request #15
Opened 2023-02-23 15:03 UTC by htemanni92

Related pull request 
https://github.com/4d/4D-Mobile-App/pull/24

2023-02-23 18:43 UTC, mesopelagique requested changes

2023-02-23 18:43 UTC, mesopelagique commented on Project/Sources/DatabaseMethods/onWebConnection.4dm
> +var $handler : cs:C1710.WebHandler
ne pas commit ca c'est juste pour le test

2023-02-23 18:43 UTC, mesopelagique commented on Project/Sources/Classes/WebHandler.4dm
> +			$signingReport:=$app["signingReport"]
ca doit pas compiler, la variable n'est pas déclarer avant 
```diff
- var $app; $object : Object
- var $app; $object; $signingReport : Object

2023-02-23 18:43 UTC, mesopelagique commented on Project/Sources/Classes/WebHandler.4dm
> +		If ($app["signingReport"]#Null:C1517)
en faite c'est la qu'il faut vérifier que si ya pas de sha256 alors ca sert a rien
donc non la tu peux rajouter une app sans sha256 

donc remonter le 	$signingReport:=$app["signingReport"] avant ici
vérifier qu'il est pas null et(`&&`) que la que tu veux existe aussi

2023-02-24 09:40 UTC, htemanni92 commented on Project/Sources/Classes/WebHandler.4dm
> +		If ($app["signingReport"]#Null:C1517)
fait

2023-02-24 09:44 UTC, htemanni92 commented on Project/Sources/Classes/WebHandler.4dm
> +			$signingReport:=$app["signingReport"]
fait

2023-02-24 09:54 UTC, htemanni92 commented on Project/Sources/DatabaseMethods/onWebConnection.4dm
> +var $handler : cs:C1710.WebHandler
fait

2023-02-27 14:07 UTC, htemanni92 commented on Project/Sources/Classes/WebHandler.4dm
> +		If ($signingReport#Null:C1517) && ($signingReport["SHA-256"]#Null:C1517)
fait

2023-02-27 14:13 UTC, merged